name: Package Synthia

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Zip the release package
      id: zip
      run: |
        mkdir -p publish/Custom/Scripts/VamDeluxe/Synthia/src
        mkdir -p publish/Custom/Scripts/VamDeluxe/Synthia/Animations
        cp -r Synthia/src/* publish/Custom/Scripts/VamDeluxe/Synthia/src/
        cp -r Synthia/Animations/* publish/Custom/Scripts/VamDeluxe/Synthia/Animations/
        cp Synthia/Synthia.cslist publish/Custom/Scripts/VamDeluxe/Synthia/
        cp Synthia/meta.json publish/
        sed -i 's/v0.0.0/v${{ github.run_number }}/' publish/meta.json
        cd publish
        zip -r "LFE.Synthia.${{ github.run_number }}.var" *
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: synthia-${{ github.run_number }}
        release_name: Release synthia-${{ github.run_number }}
        draft: false
        prerelease: false
    - name: Upload VAR
      uses: softprops/action-gh-release@v1
      with:
        tag_name: synthia-${{ github.run_number }}
        draft: false
        files: publish/LFE.Synthia.${{ github.run_number }}.var
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
